#!perl

use 5.010;
use strict;
use warnings;

use Perinci::CmdLine::Any;

# AUTHORITY
# DATE
# DIST
# VERSION

our %SPEC;

$SPEC{dist_has_deb} = {
    v => 1.1,
    summary => 'Check if dist has a corresponding Debian package',
    args => {
        dist => {
            schema => ['perl::distname*'],
            req    => 1,
            pos    => 0,
        },
        use_allpackages => {
            schema => 'bool*',
        },
    },
    links => [
        {
            url=>'prog:lcpan',
            summary => 'The lcpan debian-dist2deb subcommand',
            description => <<'_',

If you want to check multiple distribution, you can use the lcpan's
`debian-dist2deb` subcommand, which has a `--exists-on-debian` option. For
example, if you want to check PERLANCAR's distributions:

    % lcpan dists --author PERLANCAR | lcpan debian-dist2deb --exists-on-debian --use-allpackages

_
        },
    ],
};
sub dist_has_deb {
    require Dist::Util::Debian;

    my %args = @_;

    my $opts = {};
    $opts->{use_allpackages} = 1 if $args{use_allpackages};

    [200, "OK", Dist::Util::Debian::dist_has_deb($opts, $args{dist})];
}

Perinci::CmdLine::Any->new(
    url => "/main/dist_has_deb",
)->run;

# ABSTRACT:
# PODNAME:

=head1 SYNOPSIS

 % dist-has-deb HTTP::Tiny
 1

 % dist-has-deb Foo
 0


=head1 DESCRIPTION


=head1 append:SEE ALSO

L<Dist::Util::Debian>

=cut
